const segments = ["A_1_Va","A_1_Vl","A_2_Vl","A_3_Vl","Bass_1_Kb","Bass_1_Vc","Bass_2_Kb","Bass_2_Vc","Bass_3_Kb","Bass_3_Vc","B_1_Va","B_1_Vl","B_2_Va","B_2_Vl","B_3_Vl","C_1a_Vl","C_1b_Vl","C_2a_Vl","C_2b_Vl","C_3_Vl","C_4_Va","C_4_Vl","C_5_Va","C_6a_Vl","C_6b_Vl","D_1_Vl","E_1_Va","E_2_Vl","E_3_Vl","F_1_Vl","F_2_Vl","F_3_Va","F_4_Va"];
const extension = ".flac";
const measure_length = 4/3;
const measures = [
	//1
	["Bass_2_Vc"],
	[],
	["A_1_Vl"],
	["A_1_Vl"],
	//5
	["Bass_1_Vc","Bass_1_Kb","A_1_Vl"],
	["A_1_Vl"],
	["A_1_Vl"],
	["A_1_Vl"],
	//9a
	["Bass_2_Vc","Bass_2_Kb","A_1_Vl"],
	["A_1_Vl"],
	["A_1_Vl"],
	["A_1_Vl"],
	//9b
	["Bass_2_Vc","Bass_2_Kb","A_1_Vl"],
	["A_1_Vl"],
	["A_1_Vl"],
	["A_1_Vl"],
	//13
	["Bass_2_Vc","Bass_2_Kb","A_1_Vl","C_1a_Vl"],
	["A_1_Vl"],
	["A_1_Vl"],
	["A_1_Vl"],
	//17
	["Bass_2_Vc","Bass_2_Kb","A_1_Vl","C_1b_Vl"],
	["A_1_Vl"],
	["A_1_Vl"],
	["A_1_Vl"],
	//21a
	["Bass_2_Vc","Bass_2_Kb","A_1_Vl","B_1_Vl","C_4_Va"],
	["B_1_Vl","C_4_Va"],
	["B_1_Vl","C_4_Va"],
	["B_1_Vl","C_4_Va"],
	//21b
	["Bass_2_Vc","Bass_2_Kb","A_1_Vl","B_1_Vl","C_4_Va"],
	["B_1_Vl","C_4_Va"],
	["B_1_Vl","C_4_Va"],
	["B_1_Vl","C_4_Va"],
	//25a
	["Bass_2_Vc","Bass_2_Kb","A_1_Vl","C_4_Va","C_2a_Vl"],
	["A_1_Vl","C_4_Va"],
	["C_2b_Vl","A_1_Vl","C_4_Va"],
	["A_1_Vl","C_4_Va"],
	//29a
	["Bass_2_Vc","Bass_2_Kb","A_1_Vl","C_4_Va","C_2a_Vl"],
	["A_1_Vl","C_4_Va"],
	["C_3_Vl","A_1_Vl","C_4_Va"],
	["C_3_Vl","A_1_Vl","C_4_Va"],
	//25b
	["Bass_2_Vc","Bass_2_Kb","A_1_Vl","C_4_Va","C_2a_Vl"],
	["A_1_Vl","C_4_Va"],
	["C_2b_Vl","A_1_Vl","C_4_Va"],
	["A_1_Vl","C_4_Va"],
	//29b
	["Bass_2_Vc","Bass_2_Kb","A_1_Vl","C_4_Va","C_2a_Vl"],
	["A_1_Vl","C_4_Va"],
	["C_3_Vl","A_1_Vl","C_4_Va"],
	["C_3_Vl","A_1_Vl","C_4_Va"],
	//33
	["Bass_1_Vc","Bass_1_Kb","A_1_Vl","B_2_Vl","C_5_Va"],
	["A_1_Vl","B_2_Vl","C_5_Va"],
	["A_1_Vl","B_2_Vl","C_5_Va"],
	["A_1_Vl","B_2_Vl","C_5_Va"],
	//37a
	["Bass_2_Vc","Bass_2_Kb","A_1_Vl","B_2_Vl","C_5_Va"],
	["A_1_Vl","B_2_Vl","C_5_Va"],
	["A_1_Vl","B_2_Vl","C_5_Va"],
	["A_1_Vl","B_2_Vl","C_5_Va"],
	//37b
	["Bass_2_Vc","Bass_2_Kb","A_1_Vl","B_2_Vl","C_5_Va"],
	["A_1_Vl","B_2_Vl","C_5_Va"],
	["A_1_Vl","B_2_Vl","C_5_Va"],
	["A_1_Vl","B_2_Vl","C_5_Va"],
	//41
	["Bass_2_Vc","Bass_2_Kb","A_1_Vl","C_4_Vl","B_2_Va"],
	["A_1_Vl","C_4_Vl","B_2_Va"],
	["A_1_Vl","C_4_Vl","B_2_Va"],
	["A_1_Vl","C_4_Vl","B_2_Va"],
	//45
	["Bass_2_Vc","Bass_2_Kb","C_6a_Vl","A_1_Vl","B_2_Va"],
	["A_1_Vl","B_2_Va"],
	["C_6b_Vl","A_1_Vl","B_2_Va"],
	["A_1_Vl","B_2_Va"],
	//49
	["Bass_2_Vc","Bass_2_Kb","C_6a_Vl","A_1_Vl","B_2_Va"],
	["A_1_Vl","B_2_Va"],
	["C_3_Vl","A_1_Vl","B_2_Va"],
	["C_3_Vl","A_1_Vl","B_2_Va"],
	//53
	["Bass_2_Vc","Bass_2_Kb","C_6a_Vl","A_1_Vl","C_4_Va"],
	["A_1_Vl","C_4_Va"],
	["C_6b_Vl","A_1_Vl","C_4_Va"],
	["A_1_Vl","C_4_Va"],
	//57
	["Bass_2_Vc","Bass_2_Kb","C_6a_Vl","A_1_Vl","C_4_Va"],
	["A_1_Vl","C_4_Va"],
	["B_3_Vl","A_1_Vl","C_4_Va"],
	["B_3_Vl","A_1_Vl","C_4_Va"],
	//63
	["Bass_1_Vc","Bass_1_Kb","B_3_Vl","A_1_Vl","C_5_Va"],
	["B_3_Vl","A_1_Vl","C_5_Va"],
	["B_3_Vl","A_1_Vl","C_5_Va"],
	["B_3_Vl","A_1_Vl","C_5_Va"],
	//65a
	["Bass_2_Vc","Bass_2_Kb","B_3_Vl","A_1_Vl","C_5_Va"],
	["B_3_Vl","A_1_Vl","C_5_Va"],
	["B_3_Vl","A_1_Vl","C_5_Va"],
	["B_3_Vl","A_1_Vl","C_5_Va"],
	//65b
	["Bass_2_Vc","Bass_2_Kb","B_3_Vl","A_1_Vl","C_5_Va"],
	["B_3_Vl","A_1_Vl","C_5_Va"],
	["B_3_Vl","A_1_Vl","C_5_Va"],
	["B_3_Vl","A_1_Vl","C_5_Va"],
	//69
	["Bass_2_Vc","Bass_2_Kb","C_1a_Vl","A_1_Va"],
	["A_1_Va"],
	["A_1_Va"],
	["A_1_Va"],
	//73
	["Bass_2_Vc","Bass_2_Kb","C_1b_Vl","A_1_Va"],
	["A_1_Va"],
	["A_1_Va"],
	["A_1_Va"],
	//77
	["Bass_2_Vc","Bass_2_Kb","A_1_Va","A_2_Vl","D_1_Vl"],
	["A_1_Va","A_2_Vl"],
	["A_1_Va","A_2_Vl"],
	["A_1_Va","A_2_Vl"],
	//81
	["Bass_2_Vc","Bass_2_Kb","A_1_Va","A_2_Vl","A_3_Vl"],
	["A_1_Va","A_2_Vl","A_3_Vl"],
	["A_1_Va","A_2_Vl","A_3_Vl"],
	["A_1_Va","A_2_Vl","A_3_Vl"],
	//85
	["Bass_2_Vc","Bass_2_Kb","E_1_Va","E_2_Vl","E_3_Vl"],
	[],
	[],
	[],
	//89
	["Bass_3_Kb"],
	[],//treating 89 as double length
	["F_1_Vl"],
	[],
	//92
	["Bsss_3_Kb"],
	[],
	["F_2_Vl"],
	[],
	//96
	["Bass_3_Kb"],
	[],
	["F_3_Va"],
	[],
	//100
	["Bass_3_Kb"],
	[],
	["Bass_3_Vc","F_4_Va"],
	[],
	[]
]